apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runners
  namespace: actions-runner-system
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runners
  namespace: actions-runner-system
spec:
  template:
    spec:
      serviceAccountName: github-runners
      organization: sparetimecoders
      image: summerwind/actions-runner-dind:v2.299.1-ubuntu-20.04
      dockerdWithinRunnerContainer: true
      workDir: /home/runner/work
      ephemeral: true
      resources:
        limits:
          cpu: "1500m"
          memory: "2000Mi"
        requests:
          cpu: "500m"
          memory: "500Mi"
      volumeMounts:
        - mountPath: home/runner/.buildtools.yaml
          name: buildtools-config
          subPath: .buildtools.yaml
        - mountPath: home/runner/.ssh
          name: ssh-secret
      volumes:
        - name: buildtools-config
          secret:
            secretName: buildtools
            optional: true
        - name: ssh-secret
          secret:
            secretName: ssh-secret
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runners
spec:
  minReplicas: 0
  maxReplicas: 10
  scaleTargetRef:
    kind: RunnerDeployment
    name: runners
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "30m"
