apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: controller-manager
  namespace: actions-runner-system
spec:
  data:
    - secretKey: github_app_id
      remoteRef:
        key: actions-runner-system
        property: APP_ID
    - secretKey: github_app_installation_id
      remoteRef:
        key: actions-runner-system
        property: INSTALLATION_ID
    - secretKey: github_app_private_key
      remoteRef:
        key: actions-runner-system
        property: CLIENT_SECRET
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    creationPolicy: Owner
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssh-secret
  namespace: actions-runner-system
spec:
  data:
    - secretKey: id_rsa
      remoteRef:
        key: actions-runner-system
        property: SSH_KEY
    - secretKey: known_hosts
      remoteRef:
        key: actions-runner-system
        property: KNOWN_HOSTS
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    creationPolicy: Owner
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-webhook-server
  namespace: actions-runner-system
spec:
  data:
    - secretKey: github_webhook_secret_token
      remoteRef:
        key: actions-runner-system
        property: GITHUB_WEBHOOK_SECRET_TOKEN
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    creationPolicy: Owner
